services:
  Evrinoma\ArticleBundle\Controller\ArticleApiController:
    alias: evrinoma.article.article.api.controller
    public: true

  evrinoma.article.article.api.controller:
    class: Evrinoma\ArticleBundle\Controller\ArticleApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.article.article.facade'
    autowire: true

  evrinoma.article.article.facade:
    class: Evrinoma\ArticleBundle\Facade\Article\Facade
    arguments:
      - '@evrinoma.article.article.command.manager'
      - '@evrinoma.article.article.query.manager'
      - '@evrinoma.article.adaptor'
    autowire: true

  Evrinoma\ArticleBundle\Facade\Article\FacadeInterface:
    alias: evrinoma.article.article.facade

  evrinoma.article.article.factory:
    class: Evrinoma\ArticleBundle\Factory\Article\Factory
    public: true
    arguments:

  evrinoma.article.article.orm.repository:
    class: Evrinoma\ArticleBundle\Repository\Orm\Article\ArticleRepository
    public: true
    arguments:

  evrinoma.article.article.command.manager:
    class: Evrinoma\ArticleBundle\Manager\Article\CommandManager
    arguments:
      - '@evrinoma.article.article.validator'
      - '@evrinoma.article.article.repository'
      - '@evrinoma.article.article.factory'
      - '@evrinoma.article.article.command.mediator'
      - '@evrinoma.article.classifier.query.manager'
      - '@evrinoma.article.type.query.manager'

  Evrinoma\ArticleBundle\Manager\Article\CommandManagerInterface:
    alias: evrinoma.article.article.command.manager

  evrinoma.article.article.query.manager:
    class: Evrinoma\ArticleBundle\Manager\Article\QueryManager
    arguments:
      - '@evrinoma.article.article.repository'

  Evrinoma\ArticleBundle\Manager\Article\QueryManagerInterface:
    alias: evrinoma.article.article.query.manager
    
  evrinoma.article.article.validator:
    class: Evrinoma\ArticleBundle\Validator\ArticleValidator
    public: true
    arguments:

  Evrinoma\ArticleBundle\Validator\ArticleValidator:
    alias: evrinoma.article.article.validator

  evrinoma.article.article.query.orm.mediator:
    class: Evrinoma\ArticleBundle\Mediator\Article\Orm\QueryMediator
    public: true
    arguments:

  Evrinoma\ArticleBundle\Mediator\Article\Orm\QueryMediator:
    alias: evrinoma.article.article.query.orm.mediator

  evrinoma.article.article.command.mediator:
    class: Evrinoma\ArticleBundle\Mediator\Article\CommandMediator
    public: true
    arguments:
      - '@evrinoma.article.article.system.file_system'

  Evrinoma\ArticleBundle\Mediator\Article\CommandMediator:
    alias: evrinoma.article.article.command.mediator

  Evrinoma\ArticleBundle\Mediator\Article\CommandMediatorInterface:
    alias: evrinoma.article.article.command.mediator

  evrinoma.article.article.pre.validator:
    class: Evrinoma\ArticleBundle\PreValidator\Article\DtoPreValidator
    public: true
    arguments:

  Evrinoma\ArticleBundle\PreValidator\Article\DtoPreValidator:
    alias: evrinoma.article.article.pre.validator

  Evrinoma\ArticleBundle\PreValidator\Article\DtoPreValidatorInterface:
    alias: evrinoma.article.article.pre.validator

  evrinoma.article.article.system.file_system:
    class: Evrinoma\ArticleBundle\System\FileSystem
    public: true
    arguments:

  Evrinoma\ArticleBundle\System\FileSystem:
    alias: evrinoma.article.article.system.file_system

  Evrinoma\ArticleBundle\System\FileSystemInterface:
    alias: evrinoma.article.article.system.file_system