services:
  evrinoma.article.fixtures.article:
    class: Evrinoma\ArticleBundle\Fixtures\ArticleFixtures
    tags:
      - { name: doctrine.fixture.orm }

  evrinoma.article.fixtures.classifier:
    class: Evrinoma\ArticleBundle\Fixtures\ClassifierFixtures
    tags:
      - { name: doctrine.fixture.orm }

  evrinoma.article.fixtures.type:
    class: Evrinoma\ArticleBundle\Fixtures\TypeFixtures
    tags:
      - { name: doctrine.fixture.orm }
