services:
  evrinoma.article.constraint.property.article.body:
    class: Evrinoma\ArticleBundle\Constraint\Property\Article\Body

  evrinoma.article.constraint.property.article.title:
    class: Evrinoma\ArticleBundle\Constraint\Property\Article\Title

  evrinoma.article.constraint.property.article.preview:
    class: Evrinoma\ArticleBundle\Constraint\Property\Article\Preview

  evrinoma.article.constraint.property.article.active:
    class: Evrinoma\ArticleBundle\Constraint\Property\Article\Active

  evrinoma.article.constraint.property.article.position:
    class: Evrinoma\ArticleBundle\Constraint\Property\Article\Position

  evrinoma.article.constraint.property.article.image:
    class: Evrinoma\ArticleBundle\Constraint\Property\Article\Image

  evrinoma.article.constraint.property.article.description:
    class: Evrinoma\ArticleBundle\Constraint\Property\Article\Description

  evrinoma.article.constraint.complex.article.article:
    class: Evrinoma\ArticleBundle\Constraint\Complex\Article\Article
